version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - mvn test
  post_build:
    commands:
     - echo Build completed successfully
artifacts:
  files:
    - target/customer.jar
  discard-paths: yes